---
url: https://magento.nublue.co.uk
users:
  client:
    email: f7b92e34a3c14f5188@c49699c6.com
    pass: 33eef45db1c3-_#@
    company: WebJump
    address_1: Av. Pres. Juscelino Kubitschek, 50
    address_2: 7º andar
    address_3: Vila Nova Conceição
    city: São Paulo
    country: Brazil
    zip: 04543-000
    state: São Paulo
    phone: 2338-6889
