---
url: https://magento.nublue.co.uk
users:
  new_user:
    email: f4317e23fc2ea4b1df@026bc398.com
    pass: 72e2dc8e8fb0-_#@
  old_user:
    email: roni_cost@example.com
    pass: roni_cost3@example.com
