---
url: https://magento.nublue.co.uk
users:
  new_user:
    email: 78b9066c45b199210f@f22b9d4d.com
    pass: eff7c873c56e-_#@
  old_user:
    email: roni_cost@example.com
    pass: roni_cost3@example.com
