---
url: https://magento.nublue.co.uk
users:
  new_user:
    email: bdbd1102780b197205@3464a2db.com
    pass: 551895470de0-_#@
  old_user:
    email: roni_cost@example.com
    pass: roni_cost3@example.com
